version: '2'

services:
  postgresdb:
    # container IP address: docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container_id>
    image: postgres:latest
    container_name: rpg-base-template-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432

  web:
    build: .
    container_name: rpg-base-template-web
    restart: on-failure
    command: bash -c "while !</dev/tcp/postgresdb/5432; do sleep 1; done; ./bin/run_migration.sh; bundle exec ruby app.rb -o 0.0.0.0 -p 8080"
    ports:
      - 8080:8080
    environment:
       DB_CONNECTION: "postgres://${DB_USER}:${DB_PASSWORD}@postgresdb/${DB_NAME}"
    links:
      - postgresdb
    depends_on:
      - postgresdb
    volumes:
      - ./sql:/usr/app/sql