version: '3'

volumes:
  database_data:
    driver: local

services:
  postgresdb:
    image: postgres:9.6
    container_name: rpg-base-template-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  web:
    build: .
    container_name: rpg-base-template-web
    restart: on-failure
    ports:
      - 8080:8080
    environment:
       DB_CONNECTION: "postgres://${DB_USER}:${DB_PASSWORD}@postgresdb/${DB_NAME}"
    links:
      - postgresdb
